import { AlertTriangle, FileCheck2, Sparkles, Stamp } from "lucide-react";
import { prisma } from "@/lib/prisma";
import { SATIRE_LABEL } from "@/lib/satire";

export const dynamic = "force-dynamic";

export default async function SatirePage() {
  const posts = await prisma.satirePost.findMany({ where: { status: "published" }, orderBy: { publishedAt: "desc" } });
  return <div className="space-y-7"><section className="surface-dark overflow-hidden p-7 sm:p-9"><span className="inline-flex rounded-full bg-[#d7bc97] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[0.09em] text-[#241e17]">{SATIRE_LABEL}</span><h1 className="mt-5 max-w-2xl text-4xl font-semibold leading-[.95] tracking-[-0.07em] text-paper sm:text-5xl">NISHETA сводки. <span className="text-[#d6bea0]">Только вымысел.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-white/58">Это отдельная сатирическая редакция клуба. Здесь нет реальных происшествий, адресов, точных расписаний, трагедий или неподтверждённых фактов о людях.</p><div className="mt-7 flex flex-wrap gap-5 text-xs font-medium text-white/65"><span className="flex items-center gap-2"><FileCheck2 size={14} className="text-[#d6bea0]"/>Безопасные шаблоны</span><span className="flex items-center gap-2"><Stamp size={14} className="text-[#d6bea0]"/>Ревью перед публикацией</span></div></section><section><div className="page-heading"><div><p className="data-label">Редакционная лента</p><h2 className="mt-2 text-3xl font-semibold tracking-[-0.06em] text-graphite">Опубликованные материалы</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-graphite-muted">Каждая карточка публикуется только после проверки администратора и всегда остаётся в контексте пародии.</p></div></div>{posts.length ? <div className="mt-5 grid gap-4 lg:grid-cols-2">{posts.map((post) => <article key={post.id} className="surface p-5 sm:p-6"><span className="rounded-full bg-[#fcf5f0] px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.08em] text-[#a15e52]">{SATIRE_LABEL}</span><h3 className="mt-4 text-xl font-semibold leading-tight tracking-[-0.05em] text-graphite">{post.headline}</h3><p className="mt-3 text-sm leading-6 text-graphite-muted">{post.body}</p><p className="mt-5 border-t border-hairline pt-3 text-[10px] font-semibold text-graphite-muted">Редакция NISHETA · материал вымышлен</p></article>)}</div> : <div className="surface grid min-h-[340px] place-items-center p-8 text-center"><div><span className="mx-auto flex h-12 w-12 items-center justify-center rounded-2xl bg-[#f0ebe4] text-[#957752]"><Sparkles size={20}/></span><p className="mt-5 text-[10px] font-semibold uppercase tracking-[0.12em] text-[#9d8460]">{SATIRE_LABEL}</p><h3 className="mt-3 text-xl font-semibold tracking-[-0.05em] text-graphite">Редакция ещё ничего не выпустила.</h3><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-graphite-muted">Черновики создаются только из безопасных шаблонов. Перед публикацией администратор обязан проверить и явно утвердить каждый текст.</p><div className="mx-auto mt-6 flex max-w-lg items-start gap-3 rounded-xl bg-[#fbefed] p-3 text-left text-xs leading-5 text-[#99584e]"><AlertTriangle className="mt-0.5 shrink-0" size={15}/>Вымышленная трагедия, реальный адрес, точное местоположение, номер телефона или серьёзное обвинение автоматически блокируются.</div></div></div>}</section></div>;
}
